// The MIT License (MIT)
//
// Copyright (c) 2014 J.C. Moyer
//
// Permission is hereby granted, free of charge, to any person obtaining a copy
// of this software and associated documentation files (the "Software"), to deal
// in the Software without restriction, including without limitation the rights
// to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
// copies of the Software, and to permit persons to whom the Software is
// furnished to do so, subject to the following conditions:
//
// The above copyright notice and this permission notice shall be included in
// all copies or substantial portions of the Software.
//
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
// AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
// LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
// OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
// THE SOFTWARE.

#include <stdio.h>
#include <stdlib.h>
#include <string.h>

#include <lua.h>
#include <lauxlib.h>

const char* rs_int_type(int width) {
  switch (width) {
    default:
    case 2: return "c_int";
    case 4: return "c_long";
    case 8: return "c_longlong";
  }
}

const char* rs_uint_type(int width) {
  switch (width) {
    default:
    case 2: return "c_uint";
    case 4: return "c_ulong";
    case 8: return "c_ulonglong";
  }
}

// converts \ in a string to \\ so that it can be used as a rust string literal
size_t escape(const char* in, char* out, size_t szout) {
  const char* pi = in;
  char* po = out;
  int inlen = strlen(in);
  size_t written = 0;

  for (pi = in; pi < in + inlen; pi++) {
    switch (*pi) {
      case '\\':
        if (written + 2 <= szout) {
          *po++ = *pi;
          *po++ = *pi;
          written += 2;
        } else {
          return written;
        }
        break;
      default:
        if (written + 1 <= szout) {
          *po++ = *pi;
          written++;
        } else {
          return written;
        }
        break;
    }
  }

  if (written + 1 <= szout) {
    *po++ = '\0';
    written++;
  }
  return written;
}

void write_str_const(FILE* f, const char* name, const char* value) {
  size_t len = strlen(value);
  size_t bufsz = len * 2 + 1;
  char* buf = malloc(bufsz);
  escape(value, buf, bufsz);
  fprintf(f, "pub const %s: &'static str = \"%s\";\n", name, buf);
  free(buf);
}

int main(int argc, const char** argv) {
  if (argc <= 1) {
    printf("usage: %s <filename>\n", argv[0]);
    return 1;
  }

  FILE* f = fopen(argv[1], "w");

  if (!f) {
    printf("could not open file: errno = %d\n", errno);
    return 1;
  }

  fprintf(f, "/* this file was generated by glue.c; do not modify it by hand */\n");
  fprintf(f, "/* luaconf.h */\n");

  fprintf(f, "#![allow(unused_imports, dead_code, non_camel_case_types)]\n");
  fprintf(f, "use libc::{c_int, c_uint, c_long, c_ulong, c_longlong, c_ulonglong};\n");
  fprintf(f, "use libc::{c_float, c_double};\n");

  write_str_const(f, "LUA_VDIR", LUA_VDIR);
  write_str_const(f, "LUA_PATH_DEFAULT", LUA_PATH_DEFAULT);
  write_str_const(f, "LUA_CPATH_DEFAULT", LUA_CPATH_DEFAULT);
  write_str_const(f, "LUA_DIRSEP", LUA_DIRSEP);
  write_str_const(f, "LUA_ENV", LUA_ENV);

  fprintf(f, "pub const LUA_EXTRASPACE: c_int = %d;\n", LUA_EXTRASPACE);
  fprintf(f, "pub const LUA_IDSIZE: c_int = %d;\n", LUA_IDSIZE);
  fprintf(f, "pub const LUAI_MAXSHORTLEN: c_int = %d;\n", LUAI_MAXSHORTLEN);
  // LUA_CTXT?
  fprintf(f, "pub const LUAI_BITSINT: c_int = %d;\n", LUAI_BITSINT);
  // LUA_INT32? LUAI_UMEM? LUAI_MEM?
  fprintf(f, "pub const LUAI_MAXSTACK: c_int = %d;\n", LUAI_MAXSTACK);
  fprintf(f, "pub const LUAI_FIRSTPSEUDOIDX: c_int = %d;\n", LUAI_FIRSTPSEUDOIDX);
  fprintf(f, "pub const LUAL_BUFFERSIZE: c_int = %d;\n", BUFSIZ);

  if (sizeof(LUA_NUMBER) > sizeof(float)) {
    fprintf(f, "pub type LUA_NUMBER = c_double;\n");
  } else {
    fprintf(f, "pub type LUA_NUMBER = c_float;\n");
  }

  fprintf(f, "pub type LUA_UNSIGNED = %s;\n", rs_uint_type(sizeof(LUA_UNSIGNED)));
  fprintf(f, "pub type LUA_INTEGER = %s;\n", rs_int_type(sizeof(LUA_INTEGER)));
  fprintf(f, "pub const LUA_MAXINTEGER: LUA_INTEGER = "LUA_INTEGER_FMT";\n", LUA_MAXINTEGER);
  fprintf(f, "pub const LUA_MININTEGER: LUA_INTEGER = "LUA_INTEGER_FMT";\n", LUA_MININTEGER);

  fprintf(f, "/* lua.h */\n");
  write_str_const(f, "LUA_VERSION_MAJOR", LUA_VERSION_MAJOR);
  write_str_const(f, "LUA_VERSION_MINOR", LUA_VERSION_MINOR);
  fprintf(f, "pub const LUA_VERSION_NUM: c_int = %d;\n", LUA_VERSION_NUM);
  write_str_const(f, "LUA_VERSION_RELEASE", LUA_VERSION_RELEASE);

  write_str_const(f, "LUA_VERSION", LUA_VERSION);
  write_str_const(f, "LUA_RELEASE", LUA_RELEASE);
  write_str_const(f, "LUA_COPYRIGHT", LUA_COPYRIGHT);
  write_str_const(f, "LUA_AUTHORS", LUA_AUTHORS);

  fprintf(f, "/* lauxlib.h */\n");
  fprintf(f, "pub const LUAL_NUMSIZES: c_int = %d;\n", LUAL_NUMSIZES);

  fclose(f);

  return 0;
}
